src/java/modelo/CuateBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelo;

import controlador.Cuate;
import controlador.CuateBuscaInterface;
import controlador.MapeaCuates;
import java.util.Collection;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.faces.bean.SessionScoped;

/**
 *
 * @author José Alberto R
 */
@ManagedBean(name="Cuate")
@SessionScoped
public class CuateBean {

    /**
     * Creates a new instance of CuateBean
     */
    
    private String user;
    private String password;
    private Cuate cuate;
    private Collection <Cuate> ListaCuates=null; 
    
    @ManagedProperty(value="#{buscaCuates}")
    private CuateBuscaInterface cuates;
//    private static CuateBuscaInterface cuates=new MapeaCuates();
    
    public CuateBean() {
    }

    public Collection<Cuate> getListaCuates() {
        ListaCuates=cuates.ListaCuates();
        return ListaCuates;
    }
    
    
    public Cuate getCuate(){
        return cuate;
    }

    public void setCuate(Cuate cuate) {
        this.cuate = cuate;
    }

    public CuateBuscaInterface getCuates() {
        return cuates;
    }

    public void setCuates(CuateBuscaInterface cuates) {
        this.cuates = cuates;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    public String pagoCuotas(){
        String pagina="";
        cuate= cuates.BuscaCuate(user, password);
        if(cuate==null){
            pagina="Intruso";
        }
        else
            if(cuate.getCuota()>300){
                pagina="Deudor";
            }
        else
            pagina="ListaCuates";
        return pagina;
    }
    
}

web/Deudor.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <div align="center">
             
    <h:head>
        <title>DEUDOR</title>
    </h:head>
        
    <h:body>
            <ui:composition template="/Templates/master.xhtml">
            <ui:define name="titulo">
                       #{msjs.deudorHeader}
           </ui:define>
            <ui:define name="encabezado">
                <ui:include src="/secciones/cueva/header.xhtml"/>
            </ui:define>
            
            <ui:define name="lado">
                <ui:include src="/secciones/cueva/LadoIzq.xhtml"/>
            </ui:define>
            
            <ui:define name="contenido">
                <div align="center" style="color: red">
                <br></br>        
                <h:graphicImage library="img" name="d2.jpg"/>
                <h3  align="center" style=" border:darkred double thick ">#{msjs.deudor}&nbsp;#{Cuate.cuate.nombres}&nbsp;#{Cuate.cuate.apellidos}&nbsp;PAGUE O SERA CONSIGNADO (A) A LAS AUTORIDADES!!</h3>
               
               <h:dataTable  value="#{Cuate.cuate}" var="cuate"  style="border: red double thick "  styleClass="tabla" captionClass="caption" rowClasses="impari,par" cellpadding="4 " cellspacing="2">
                            <f:facet name="caption">#{conf.PageTitulo}</f:facet>
                
                            <h:column headerClass="header" footerClass="pie">
                                <f:facet name="header">Nombre</f:facet>
                                #{Cuate.cuate.nombres}&nbsp;&nbsp;&nbsp;#{Cuate.cuate.apellidos}
                            </h:column>

                            <h:column headerClass="header" footerClass="pie"  >
                                <f:facet name="header">#{msjs.IntrusoHeader}</f:facet>
                                <h:graphicImage library="img" name="#{cuate.foto}.png"/>
                            
                            </h:column>
                            
                 </h:dataTable>

                <h:form>
                 <h:commandButton action="index.xhtml" value="inicio"/>
                </h:form>
                
                </div>
               
            </ui:define>
        </ui:composition>
    </h:body>
   </div>
</html>

web/Intruso.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>INTRUSO</title>
    </h:head>
    <h:body>
            <ui:composition template="/Templates/master.xhtml">
            <ui:define name="titulo">
            </ui:define>
            
            <ui:define name="encabezado">
            <ui:include src="/secciones/cueva/header.xhtml"/>
            </ui:define>
            
            <ui:define name="lado">
                <ui:include src="/secciones/cueva/LadoIzq.xhtml"/>
            </ui:define>
                
            <br></br>
            <ui:define name="contenido">
                <center>
                <h:graphicImage  library="img" name="warning.jpg" style=" alignment-adjust:  central"/>
                <br></br>
                <h:graphicImage  library="img" name="gifs.gif" style=" alignment-adjust:  central"/>
                <h1 align="center"  style="color:red " > #{msjs.AlertaIntruso}</h1>
                <h3 style=" color:  firebrick" class=" LadoIzdLogin">#{msjs.HeaderIntruso}</h3>
                    
                <br></br>
                <h:form>
                <h:commandButton action="index.xhtml" value="inicio"/>
                
                </h:form>
               </center>
                
                
            </ui:define>
        </ui:composition>
    </h:body>
</html>

web/ListaCuates.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

    <h:head>
        <title>#{conf.listaPage1Titulo}</title>

    </h:head>
    <h:body styleClass="msj">
        <div align="center">


            <h:outputStylesheet library="css" name="estilos.css"></h:outputStylesheet>
            <ui:composition template="/Templates/master.xhtml">
                <ui:define name="titulo">
                    #{msjs.ListaCuate}&nbsp;#{Cuate.user}
                </ui:define>
                <ui:define name="encabezado">
                    <ui:include src="/secciones/cueva/header.xhtml"/>
                </ui:define>

                <ui:define name="lado">
                    <ui:include src="/secciones/cueva/LadoIzq.xhtml"/>
                </ui:define>
                <ui:define name="contenido">

                    <hr/>
                    <h:form>
                        <div align="center">
                            <h:dataTable  value="#{Cuate.listaCuates}" var="cuate" styleClass="tabla" captionClass="caption" rowClasses="impari,par" cellpadding="4
                                          " cellspacing="7">

                                <h:column headerClass="header" footerClass="pie"  >
                                    <f:facet name="header">#{msjs.headercolumna1}</f:facet>
                                        #{cuate.apellidos}

                                </h:column>
                                <h:column headerClass="header" footerClass="pie" >
                                    <f:facet name="header">#{msjs.headercolumna2}</f:facet>
                                    &nbsp;&nbsp;#{cuate.nombres}

                                </h:column>
                                <h:column headerClass="header" footerClass="pie"  transient="">
                                    <f:facet name="header">#{msjs.headercolumna3}</f:facet>
                                    &nbsp;&nbsp; #{cuate.cuota}

                                </h:column>

                                <h:column headerClass="header" footerClass="pie">
                                    <f:facet name="header">#{msjs.IntrusoHeader}</f:facet>
                                    <h:graphicImage library="img" name="#{cuate.foto}.png"/>

                                </h:column>

                            </h:dataTable>
                            
                            <h:commandButton action="index.xhtml" value="inicio" style=" color: whitesmoke; font-style:  italic; background: #000"/>
                        </div>

                    </h:form>
                </ui:define>
            </ui:composition>
        </div>
    </h:body>
</html>

web/Templates/master.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title><ui:insert name="titulo"/> </title>
        <h:outputStylesheet library="css" name="estilos.css"/>
    </h:head>
    
    <h:body>
        <div id="encavezado">
            <ui:insert name="encavezado">
                <ui:include src="../secciones/cueva/header.xhtml"/>
            </ui:insert>
        </div> 
        
        <div id="lado">
            <ui:insert name="lado">
                <ui:include src="../secciones/cueva/LadoIzq.xhtml"/>
            </ui:insert>
        </div>
        
        <div id="contenido">
            <ui:insert name="contenido"/>
        </div> 
    </h:body>
</html>

web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>#{msjs.index}</title>
        <h:outputStylesheet library="css" name="estilos.css"/>
    </h:head>
    <h:body>
        <ui:composition template="/Templates/master.xhtml">
            <ui:define name="titulo" class="header">Templates
            </ui:define>
            <ui:define name="encabezado">
                <ui:include src="/secciones/login/header.xhtml"/>
            </ui:define>
            <ui:define name="lado">
                <ui:include src="/secciones/login/LadoIzq.xhtml"/>
            </ui:define>
            <div align="center">
                <ui:define name="contenido">
                    <br/>
                    <h:form>
                        <div align="center"  style=" color: white; font-size:  x-large; font-family: cursive">
                            <h:panelGrid  columns="2" cellpadding="0"  cellspacing="1"  border="3">
                                <b>#{msjs.usuario}</b>
                                <h:inputText value="#{Cuate.user}"/>
                                <br/>
                                <b>#{msjs.password}</b>
                                <h:inputSecret value="#{Cuate.password}"/>
                            </h:panelGrid>
                        </div>
                        <br/>
                        <div align="center" style="color: white">
                            <h:panelGrid  columns="1" cellpadding="2"  cellspacing="2">
                                <h:panelGroup>
                                    <h:commandButton value="Enviar" action="#{Cuate.pagoCuotas()}" style=" color: whitesmoke; font-style:  italic; background: #000"/>
                                    <h:commandButton value="Cancelar" style=" color: whitesmoke; font-style:  italic; background: #000"/>
                                </h:panelGroup>
                            </h:panelGrid> 
                        </div>
                    </h:form>
                </ui:define>
            </div>
        </ui:composition>
    </h:body>
</html>

web/secciones/cueva/LadoIzq.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>IGNORADO</title>
    </h:head>
    <h:body>
        <ui:composition>
            <div class="LadoIzdCueva">
                #{msjs.ladocueva} 
                <div class="LadoIzqImg" style=" background: darkgrey " align="right">
                    <br></br>
                    <center> <h:graphicImage  library="img" name="logocueva.gif"  /> </center>
                    <br></br>
                </div>
            </div>
        </ui:composition>
    </h:body>
</html>

web/secciones/cueva/header.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>IGNORADO</title>
    </h:head>
    <h:body>
        <ui:composition>
            <div align="center" class="header" style="border-bottom-style:  groove;
                 color:chartreuse;
                 font-family:cursive">
                #{msjs.indexHeader}
            </div>
        </ui:composition>
    </h:body>
</html>

web/secciones/login/LadoIzq.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>IGNORADO</title>
    </h:head>
    <h:body>
        <ui:composition>
            <div class="LadoIzdLogin" style="background-color: lightseagreen; font-family:  fantasy; color:  antiquewhite;" align="center">
                #{msjs.LadoLogin1} 
                <br/>
                 #{msjs.LadoLogin2} 
                <div class="LadoIzqImg" style="background-color:  aqua" align="center">
                    <h:graphicImage  library="img" name="logocueva.gif"/>
                    
                </div>
            </div>
        </ui:composition>
    </h:body>
</html>

web/secciones/login/header.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>IGNORADO</title>
    </h:head>
    <h:body>
        <ui:composition>
            <div align="center" class="header" style=" border-style:  double; background-color:  blue" >
                #{msjs.indexHeader}
            </div>
        </ui:composition>
    </h:body>
</html>